### ISSUE TITLE
Any help needed

### ISSUE THREAD

**Issue by aspglak** [BerkeleyTrue/react-redux-epic#1]
I'm current using redux-epic to handle async side effects in a universal app. As there doesn't seem to be a big community behind it and documentation (Besides the code you've written using it in freecodecamp) I would really like to be able to use redux-observable with SSR. 

If you need help I'll be happy to give you a hand - even two :).

Let me know.

Thanks

**Comment by BerkeleyTrue** [comment]
My goal is to get some tests up and running within the next week. Once those are running I'll need people to start using it and let me know if they run into any problems 😉

**Comment by aspglak** [comment]
@BerkeleyTrue I'll be there to start using it and tell if you if I run into any bugs ;) 

Thanks

**Comment by BerkeleyTrue** [comment]
@aspglak I cut a release last week and was able to get a version running for one of my workshops here https://github.com/realworldreact/react-shoppe/tree/intro-rx-backup

But a second version would not complete for some reason. 
https://github.com/realworldreact/react-shoppe/tree/intro-rx

So there are still some bugs to be worked out.

Let me know how you find it.

**Comment by BerkeleyTrue** [comment]
Looks like this project is in working condition. Let me know if you are able to try it out. 

Happy Coding!
