### ISSUE TITLE
Reduce module weight

### ISSUE THREAD

**Issue by Bouncey** [BerkeleyTrue/react-redux-epic#22]
This module is SUPER heavy!

![react-redux-epic](https://user-images.githubusercontent.com/18572518/31307207-c7a0b5e2-ab56-11e7-960d-c3621d50dd78.png)
Even doing a direct import with `import { wrapRootEpic } from 'react-redux-epic/lib/wrap-root-epic';` has a size 208.5K (39.6K gziped)

Consider using webpack or rollup and specifying externals of `rxjs` and `redux-observable` so they are not included in this module.
I think it would be sae to assume that anyone using this module already has those deps

**Comment by Bouncey** [comment]
For compasion:

react is 44K (13.7K gziped)
rxjs is 199.1K (36K gziped)

**Comment by BerkeleyTrue** [comment]
Hey @Bouncey,

I apologize for the lack of documentation. 

`wrapRootEpic` isn't really required clientside. 

There is `react-redux-epic/client` that will let you import the client side version of `wrapRootEpic` as well as the `render` method. This version of `wrapRootEpic` is just an identity function.

https://github.com/BerkeleyTrue/react-redux-epic/blob/master/client.js

Here are the docs for the client side stuff https://github.com/BerkeleyTrue/react-redux-epic/blob/master/docs/api/README.md#usage-2

But it is clearly missing the `wrapRootEpic` method.

It also doesn't mention that these client-side methods are completely optional and are there for symmetry more than anything.

Let me know if this reduces your bundle size.
