### ISSUE TITLE
Safe to use in production yet?

### ISSUE THREAD

**Issue by dawidvdh** [BerkeleyTrue/react-redux-epic#3]
Hi @BerkeleyTrue, 

I have been following the threads on [redux-observable](https://github.com/redux-observable/redux-observable) concerning SSR, I was just wondering if this was safe to use in production yet? Or do you have another temporary recommended method while this is being created still?

Any Help would be greatly appreciated.

**Comment by BerkeleyTrue** [comment]
I think that is going to be a judgement call on you rather than any final word I can give. The code written is with production in mind but I have yet to switch over to Redux-Observable from Redux-Epic

**Comment by dawidvdh** [comment]
Awesome, Thank you for your answer :)
