### ISSUE TITLE
support dependency injection

### ISSUE THREAD

**Issue by cometta** [BerkeleyTrue/react-redux-epic#4]
are you able to support below for SSR ?

const epicMiddleware = createEpicMiddleware(rootEpic, {
  dependencies: { getJSON: ajax.getJSON }
});

and later
const fetchUserEpic = (action$, store, { getJSON }) =>

**Comment by BerkeleyTrue** [comment]
Yes, RRE does not interfere with the other arguments used in epics. Are you having difficulties getting this to work?
